Magic store to db
RnDAO/tc-botComm pull request #54
Opened 2023-01-06 18:04 UTC by magicpalmtree

1. Insert messages with updated schema
2. Add env.sample

Below is updated rawinfo schema(created_at and channelId added).
<pre>
{
  id: unsigned integer: "message id",
  type: string: "type of message" (default or reply or guild member or something),
  created_at: Datetime: "date time of message",
  author: string: "author of message",
  content: string: "content of message",
  user_Mentions: String Array: "list of mentioned users",
  roles_Mentions: String Array: "list of mentioned roles",
  reactions: String Array: "list of reactions",
  replied_User: String: "replied message user",
  reference_Message: unsigned integer: "replied message id",
  channel_Id: unsigned integer: "id of channel or thread",
}
</pre>

2023-01-06 19:27 UTC, mehrdadmms approved these changes

2023-01-11 22:45 UTC, mehrdadmms requested changes

2023-01-11 22:45 UTC, mehrdadmms commented on .env.sample
> +LOCAL='mongodb+srv://root:root@cluster0.mgy22jx.mongodb.net/test'
Please DO NOT share credentials

```suggestion
DATABASE=XXX
DB_USER=XXX
DB_PASSWORD=XXX
LOCAL=XXX
```

2023-01-11 22:46 UTC, mehrdadmms commented
Please also mention in your pull request which issues you're trying to close, this way when I merge Github will automatically close the issue.

2023-01-11 23:42 UTC, magicpalmtree commented
Sorry for the PR comment.
This is just for resolve #55

2023-01-12 16:46 UTC, mehrdadmms approved these changes

2023-01-12 16:46 UTC, merged