Magic fetch
RnDAO/tc-botComm pull request #56
Opened 2023-01-12 21:14 UTC by magicpalmtree

resolve #53 
1. fetch settings from RnDAO guild database.
2. fetch messages from discord upon each setting.
3. insert missed messages to the database.
4. after each setting's action, notice to user.

2023-01-15 18:06 UTC, mehrdadmms requested changes

2023-01-15 18:06 UTC, mehrdadmms commented on index.js
> +      noticeToUser(client, user, "Extracted successfully.");
There's no need for sending a message back to user. Actually the user is a "TogetherCrew" user not a "Discord" user hence, you can't even send a message to that user. 

This script is going to be scheduled, and the data will be stored in DB.

2023-01-19 18:52 UTC, mehrdadmms requested changes

2023-01-19 18:52 UTC, mehrdadmms commented on action/export.js
> +};
```suggestion
```

2023-01-19 18:52 UTC, mehrdadmms commented on action/export.js
> +  noticeToUser
```suggestion
```

2023-01-19 18:52 UTC, mehrdadmms commented on database/dbservice.js
> +  const guildId = process.env.GUILD;
Why the guilds are coming from env ? 
We've got a db called RnDAO which we store all the guilds in it and for each guild we have a different settings which you need to go through, then for each guild there's a DB which you can store the raw data

2023-01-19 18:52 UTC, mehrdadmms commented on index.js
> +      await insertMessages(guildId, missed);
In this section your fetching all messages from discord and check it against the messages we already have. this is ok for small amounts for example for 2 days but imagine the period is one year. then you need to fetch millions of messages and then compare them. also what if you extracted all the messages once and you just need the messages from yesterday ? 

The better solution is to first compare the period against what we already got in database then figure out the missing periods (from the beginning and the end) then start fetching the information which falls into the missing period

2023-01-19 23:33 UTC, magicpalmtree commented on database/dbservice.js
> +  const guildId = process.env.GUILD;
Yes, I know.
There, process.env.GUILD is "RnDAO".
Through that function, we can get all different guild settings from RnDAO database

2023-01-19 23:50 UTC, magicpalmtree commented on index.js
> +      await insertMessages(guildId, missed);
I thought that problem, that solution is possible when the data stored in the database are in one time range.
e.x: all data are from 5 days ago to yesterday. In this case, we can confirm the time range by getting oldest and latest message from database.
But if there are several time range data like [10 days ago, 8 days ago], [6 days ago, 4 days ago], [2 days ago, yesterday],
then we have to iterate all messages to figure out missing periods.

The solution is to save time period fetched in the past and can figure out missing periods.

====One issue===
If someone edits the old messages, then we have to update the message in the database.
We have to consider this?

2023-01-20 00:01 UTC, magicpalmtree commented on index.js
> +      await insertMessages(guildId, missed);
====One issue===
If someone edits the old messages, then we have to update the message in the database.
We have to consider this?

2023-01-20 00:01 UTC, magicpalmtree commented
====One issue===
If someone edits the old messages, then we have to update the message in the database.
We have to consider this?

2023-01-20 05:10 UTC, mehrdadmms commented on index.js
> +      await insertMessages(guildId, missed);
So actually there aren't different time ranges. User will select a start time in settings section and we should always have the data from that date till now. this script should be designed in such a way that extract the information from starting date till now this way we can consider there aren't any gaps in the extracted data and we can always assume we need to get the additional data.

Also we're not going to handle the changes in previous data, because the number of edited messages after a day is not a considerable amount hence, we can ignore them or at least we can update a few days back and upsert the messages, not the whole time period.

Getting the whole time period is impossible because as the time ranges gets bigger and bigger the amount of data is going to exponentially grow. On the other hand we've got multiple guilds which we need to export the information for and we need to export all of this information in a timely manner.

2023-01-20 15:56 UTC, magicpalmtree commented on index.js
> +      await insertMessages(guildId, missed);
If we can assume that there are no gaps in time range, no problem.
I will update soon.

2023-01-25 19:07 UTC, mehrdadmms commented on action/export.js
> +              let threadPromise = Promise.resolve();
I don't understand the purpose of `Promise.resolve()` here?
Also the whole function is very complex, would you please explain it.

2023-01-25 19:11 UTC, mehrdadmms commented on index.js
> +  await promise;
Please explain this as well

2023-01-25 22:32 UTC, mehrdadmms commented on index.js
> +  await promise;
```suggestion
      const promises = settings.forEach(async setting => {
        const {guildId} = setting;
        // fetch missed messages from discord
        const messages = await fetch(setting);
        // insert messages to the database
        await insertMessages(guildId, messages);
    });
    await Promise.all(promises)
```

I think this code does the same thing as your method but isn't this much more straight forward ?

2023-01-25 23:02 UTC, mehrdadmms commented
I'm trying to run the code but it doesn't work properly. 
Not only I don't get any messages, but there is also some weird behavior in the code. 
I added some logs in the code (indicated with the red rectangle)
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/35366864/214710832-d636080b-8963-4a9b-9519-c021abf5fb4f.png">
then I ran the code, here's the log
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/35366864/214711156-289bae99-dcf3-4cd4-ba9c-aebddabb6aa7.png">
Again if you pay attention to the red rectangle section of logs you can see that your code is not finishing its job. somehow there's a race situation and the `993163081939165234` guild replaces the `1037490021462179910` guild in the procedure.

2023-01-25 23:52 UTC, mehrdadmms commented on index.js
> +    const channels = selectedChannels.map(item => item.channelName);
Please use channel id instead of channel name when you're filtering the channels to fetch their messages.
The channel name can change over time but we don't necessarily update the name but if you use channel id we can avoid this issue

2023-01-26 00:15 UTC, mehrdadmms commented
# Summery
Finally, I was able to run it. it works properly and extracts the information. There is only one **critical** issue.
if I run the code twice it will create duplicate records.
As we discussed, if you have the raw information in the database you shouldn't fetch them anymore but this isn't the case at the moment.

# More info 
Here are some screenshots for you indicating the issue.
As you can see, I have a duplicate of one of the messages
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/35366864/214723348-964b5534-be20-4393-9230-8f3aeb3377cb.png">
Also as indicated below there are around 241 messages 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/35366864/214723441-4bb4be92-5d46-4bc2-ae5b-4637802c0a6d.png">
but since I ran the code twice I've got more than 600 documents 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/35366864/214723428-5edf61e7-7079-4694-a32f-8ddd94aa27a4.png">

2023-01-26 02:57 UTC, magicpalmtree commented on index.js
> +  await promise;
Yes, More simple and straightforward.
Thanks very much.
I will replace it.

2023-01-26 14:24 UTC, magicpalmtree commented on database/dbservice.js
> +  const guildName = "RnDAO";
I fixed.

2023-01-26 14:25 UTC, magicpalmtree commented on index.js
> +    const channels = selectedChannels.map(item => item.channelName);
I updated with channel id.

2023-01-29 17:44 UTC, mehrdadmms approved these changes

2023-01-29 17:45 UTC, merged